# Generated by Django 2.2.8 on 2020-01-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191223_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, upload_to='galeria'),
        ),
    ]
