# Generated by Django 2.2.8 on 2020-01-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200108_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='galeria'),
        ),
    ]
